context:
  version: "0.2.127"

package:
  name: wasm-bindgen-cli
  version: ${{ version }}

source:
  url: https://static.crates.io/crates/wasm-bindgen-cli/wasm-bindgen-cli-${{ version }}.crate
  sha256: 6123f525ba36df42e57b67027637a78591e712a9f6a025ffd3d74298fa1c3f4c

build:
  number: 1
  script:
    - if: win
      then:
        - set CARGO_HOME=C:\\.cargo
        - md %CARGO_HOME%
    - tar -xzf wasm-bindgen-cli-${{ version }}.crate --strip-components=1
    - cargo install --locked --no-track --root ${{ PREFIX }} --path .
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  files:
    - bin/wasm-bindgen
    - bin/wasm-bindgen.exe
    - bin/wasm-bindgen-test-runner
    - bin/wasm-bindgen-test-runner.exe
    - bin/wasm2es6js
    - bin/wasm2es6js.exe

requirements:
  build:
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses

tests:
  - script:
      - if: build_platform == target_platform
        then: wasm-bindgen --version
  - package_contents:
      bin:
        - wasm-bindgen
        - wasm-bindgen-test-runner
        - wasm2es6js

about:
  homepage: https://wasm-bindgen.github.io/wasm-bindgen/
  summary: Command line interface for wasm-bindgen
  description: |
    Command line interface for the wasm-bindgen project.
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml
  documentation: https://wasm-bindgen.github.io/wasm-bindgen/
  repository: https://github.com/wasm-bindgen/wasm-bindgen

extra:
  recipe-maintainers:
    - timkpaine
